-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT hub.ID AS ENTITY_ID, hub.NAME AS ENTITY_NAME,
       hub.REGION, hub.CATEGORY, hub.STATUS,
       COUNT(*) AS EVENT_COUNT, SUM(observation.DISRUPTION_COUNT) AS DISRUPTION_COUNT,
       SUM(observation.OPERATING_HOURS) AS OPERATING_HOURS,
       SUM(observation.PLANNED_HOURS) AS PLANNED_HOURS,
       SUM(observation.DOWNTIME_HOURS) AS DOWNTIME_HOURS,
       SUM(observation.PM_DUE) AS PM_DUE, SUM(observation.PM_COMPLETED) AS PM_COMPLETED,
       SUM(observation.COURIER_ROUTES) AS COURIER_ROUTES,
       SUM(observation.ON_TIME_PARCELS) AS ON_TIME_PARCELS, SUM(observation.PARCELS) AS PARCELS,
       SUM(observation.FAILED_ATTEMPTS) AS FAILED_ATTEMPTS,
       100.0 * SUM(observation.ON_TIME_PARCELS) / NULLIF(SUM(observation.PARCELS), 0) AS ON_TIME_PCT,
       1000.0 * SUM(observation.FAILED_ATTEMPTS) / NULLIF(SUM(observation.PARCELS), 0) AS FAILED_PER_1K,
       100.0 * SUM(observation.OPERATING_HOURS) / NULLIF(SUM(observation.PLANNED_HOURS), 0) AS SORTER_UPTIME_PCT,
       100.0 * SUM(observation.PM_COMPLETED) / NULLIF(SUM(observation.PM_DUE), 0) AS PM_COMPLIANCE_PCT,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.HUB_DAILY observation
JOIN RAW.HUBS hub ON hub.ID = observation.ENTITY_ID
GROUP BY hub.ID, hub.NAME, hub.REGION, hub.CATEGORY, hub.STATUS;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(ON_TIME_PARCELS) AS ON_TIME_PARCELS, SUM(PARCELS) AS PARCELS,
       SUM(COURIER_ROUTES) AS COURIER_ROUTES, SUM(FAILED_ATTEMPTS) AS FAILED_ATTEMPTS,
       SUM(DISRUPTION_COUNT) AS DISRUPTION_COUNT,
       100.0 * SUM(ON_TIME_PARCELS) / NULLIF(SUM(PARCELS), 0) AS ON_TIME_PCT
FROM RAW.HUB_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.DISRUPTION_CAUSES
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT ROOT_CAUSE, SUM(DISRUPTION_COUNT) AS DISRUPTION_COUNT,
       SUM(DOWNTIME_HOURS) AS DOWNTIME_HOURS,
       SUM(PARCELS) - SUM(ON_TIME_PARCELS) AS LATE_PARCELS
FROM RAW.HUB_DAILY
WHERE DISRUPTION_COUNT > 0
GROUP BY ROOT_CAUSE;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(ON_TIME_PARCELS) AS ON_TIME_PARCELS, SUM(PARCELS) AS PARCELS,
         SUM(COURIER_ROUTES) AS COURIER_ROUTES, SUM(FAILED_ATTEMPTS) AS FAILED,
         SUM(DISRUPTION_COUNT) AS DISRUPTIONS,
         SUM(OPERATING_HOURS) AS OPERATING_HOURS, SUM(PLANNED_HOURS) AS PLANNED_HOURS,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.HUB_DAILY
), fleet AS (SELECT COUNT(*) AS HUB_COUNT FROM RAW.HUBS),
readiness AS (
  SELECT 100.0 * SUM(LEAST(ON_HAND_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT
  FROM RAW.FLEET_READINESS
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'On-Time Delivery' AS TITLE,
         100.0 * ON_TIME_PARCELS / NULLIF(PARCELS, 0) AS VALUE_NUM, '%' AS UNIT FROM observations
  UNION ALL SELECT 2, 'Delivery Disruptions', DISRUPTIONS, '' FROM observations
  UNION ALL SELECT 3, 'Failed Attempts per 1k', 1000.0 * FAILED / NULLIF(PARCELS, 0), '' FROM observations
  UNION ALL SELECT 4, 'Parcels Handled', PARCELS, '' FROM observations
  UNION ALL SELECT 5, 'Sorter Uptime', 100.0 * OPERATING_HOURS / NULLIF(PLANNED_HOURS, 0), '%' FROM observations
  UNION ALL SELECT 6, 'Hubs Monitored', HUB_COUNT, '' FROM fleet
  UNION ALL SELECT 7, 'Fleet Readiness', COVERAGE_PCT, '%' FROM readiness
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.TITLE = 'Failed Attempts per 1k' THEN TRIM(TO_VARCHAR(metrics.VALUE_NUM, '990.00'))
                WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.DISRUPTION_CAUSES SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
