-- Generated from generator/demo_specs/aws-indonesia-digital-economy-logistics.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-indonesia-digital-economy-logistics
-- This is the schema that is actually deployed for ID_DIGITAL_ECONOMY_LOGISTICS.

-- Alerts fire on the bottom tail of On-Time Rate
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_ON_TIME_RATE) AS T
  FROM RAW.DELIVERIES
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_ON_TIME_RATE <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_ON_TIME_RATE), 2) AS AVG_ON_TIME_RATE,
  ROUND(AVG(f.KPI_AVG_DELIVERY_TIME), 2) AS AVG_DELIVERY_TIME,
  ROUND(AVG(f.KPI_ROUTE_EFFICIENCY), 2) AS AVG_ROUTE_EFFICIENCY
FROM RAW.DELIVERIES f
JOIN RAW.LOGISTICS_DOCS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_ON_TIME_RATE), 2) AS AVG_ON_TIME_RATE,
  ROUND(AVG(f.KPI_AVG_DELIVERY_TIME), 2) AS AVG_DELIVERY_TIME,
  ROUND(AVG(f.KPI_ROUTE_EFFICIENCY), 2) AS AVG_ROUTE_EFFICIENCY
FROM RAW.DELIVERIES f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_ON_TIME_RATE) AS KPI_ON_TIME_RATE, AVG(KPI_AVG_DELIVERY_TIME) AS KPI_AVG_DELIVERY_TIME, AVG(KPI_ROUTE_EFFICIENCY) AS KPI_ROUTE_EFFICIENCY FROM RAW.DELIVERIES),
     en AS (SELECT SUM(KPI_DELIVERIES_MTD) AS KPI_DELIVERIES_MTD, SUM(KPI_ACTIVE_RIDERS) AS KPI_ACTIVE_RIDERS, SUM(KPI_FUEL_COST_SAVED) AS KPI_FUEL_COST_SAVED, SUM(KPI_FAILED_DELIVERIES) AS KPI_FAILED_DELIVERIES FROM RAW.LOGISTICS_DOCS)
  SELECT 1 AS SORT_ORDER, 'Deliveries (MTD)' AS TITLE, KPI_DELIVERIES_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_DELIVERIES_MTD) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'On-Time Rate' AS TITLE, KPI_ON_TIME_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ON_TIME_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Avg Delivery Time' AS TITLE, KPI_AVG_DELIVERY_TIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_DELIVERY_TIME), 1) AS DECIMAL(38,1))) || ' ' || 'days' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Active Riders' AS TITLE, KPI_ACTIVE_RIDERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_ACTIVE_RIDERS) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Fuel Cost Saved' AS TITLE, KPI_FUEL_COST_SAVED AS VALUE_NUM, 'Rp' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_FUEL_COST_SAVED) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Route Efficiency' AS TITLE, KPI_ROUTE_EFFICIENCY AS VALUE_NUM, '+' || TO_VARCHAR(CAST(ROUND((KPI_ROUTE_EFFICIENCY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Failed Deliveries' AS TITLE, KPI_FAILED_DELIVERIES AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FAILED_DELIVERIES), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
