-- Disruption-risk scoring and parcel-volume forecast over the synthetic snapshot.
-- Predicts P(delivery disruption in the next 7 days) per hub and reports
-- out-of-time holdout metrics; nothing is seeded as a prediction.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.DISRUPTION_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, t.CATEGORY, t.AGE_YEARS,
       r.DWELL_HOURS, r.SORTER_LOAD_PCT,
       AVG(r.DWELL_HOURS) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS DWELL_7D,
       SUM(r.DISRUPTION_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS DISRUPTIONS_30D,
       IFF(SUM(r.DISRUPTION_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) > 0,
           'DISRUPTION', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) AS FUTURE_DAYS
FROM RAW.HUB_DAILY r JOIN RAW.HUBS t ON t.ID = r.ENTITY_ID
-- Regional events (flood, ferry suspension) are not hub-driven, so they are excluded from training.
WHERE r.ROOT_CAUSE NOT IN ('Flood road closure', 'Ferry suspension (weather)') OR r.DISRUPTION_COUNT = 0;

-- Time-based split: train on older labelled days, hold out the most recent 14 labelled days.
CREATE VIEW ML.DISRUPTION_TRAIN AS
SELECT CATEGORY, AGE_YEARS, DWELL_HOURS, SORTER_LOAD_PCT, DWELL_7D, DISRUPTIONS_30D, LABEL
FROM ML.DISRUPTION_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE < DATEADD('day', -21, CURRENT_DATE());

CREATE VIEW ML.DISRUPTION_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, AGE_YEARS, DWELL_HOURS, SORTER_LOAD_PCT, DWELL_7D, DISRUPTIONS_30D, LABEL
FROM ML.DISRUPTION_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE >= DATEADD('day', -21, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.DISRUPTION_RISK_MODEL(
  INPUT_DATA => TABLE(ML.DISRUPTION_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.DISRUPTION_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.DISRUPTION_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'AGE_YEARS', AGE_YEARS, 'DWELL_HOURS', DWELL_HOURS,
           'SORTER_LOAD_PCT', SORTER_LOAD_PCT, 'DWELL_7D', DWELL_7D, 'DISRUPTIONS_30D', DISRUPTIONS_30D)):probability:DISRUPTION::FLOAT AS P
  FROM ML.DISRUPTION_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'DISRUPTION', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'DISRUPTION', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'DISRUPTION', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'DISRUPTION', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per hub (label unknown, so excluded from features).
CREATE TABLE ML.DISRUPTION_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.DISRUPTION_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.DISRUPTION_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'AGE_YEARS', AGE_YEARS, 'DWELL_HOURS', DWELL_HOURS,
           'SORTER_LOAD_PCT', SORTER_LOAD_PCT, 'DWELL_7D', DWELL_7D, 'DISRUPTIONS_30D', DISRUPTIONS_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:DISRUPTION::FLOAT, 4) AS DISRUPTION_PROB_7D,
       CASE WHEN P:probability:DISRUPTION::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:DISRUPTION::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Network-wide parcel-volume forecast (14 days) from the daily series.
CREATE VIEW ML.DAILY_VOLUME AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, SUM(PARCELS)::FLOAT AS PARCELS
FROM RAW.HUB_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.VOLUME_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_VOLUME),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'PARCELS'
);

CREATE TABLE ML.VOLUME_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, ROUND(FORECAST) AS PARCELS,
       ROUND(GREATEST(0, LOWER_BOUND)) AS LOWER_BOUND, ROUND(UPPER_BOUND) AS UPPER_BOUND
FROM TABLE(ML.VOLUME_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
