-- ============================================================================
-- 99_RESET.SQL — Reset Last-Mile Logistics Optimization to clean demo state
-- ============================================================================
USE DATABASE LOGISTICS_OPTIMIZATION;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_REFRESH_DELIVERIES SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_VOLUME SUSPEND;
ALTER TASK IF EXISTS APP.TASK_OPTIMIZE_ROUTES SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.DELIVERY_PERFORMANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.HUB_CAPACITY REFRESH;
ALTER DYNAMIC TABLE CURATED.ROUTE_EFFICIENCY REFRESH;
ALTER DYNAMIC TABLE CURATED.DRIVER_PRODUCTIVITY REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM LOGISTICS_OPTIMIZATION.RAW.DELIVERIES → 30000000
-- SELECT COUNT(*) FROM LOGISTICS_OPTIMIZATION.RAW.HUBS → 500
-- SELECT COUNT(*) FROM LOGISTICS_OPTIMIZATION.RAW.FLEET → 15000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_OPTIMIZE_ROUTES RESUME;
ALTER TASK IF EXISTS APP.TASK_FORECAST_VOLUME RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_DELIVERIES RESUME;
